//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advance_Tran
    {
        public int iAdv_Cd { get; set; }
        public Nullable<System.DateTime> dAdv_Dt { get; set; }
        public Nullable<System.DateTime> dMain_Dt { get; set; }
        public string sGuest { get; set; }
        public string sMobile { get; set; }
        public string sPax { get; set; }
        public string sTime { get; set; }
        public string Remark { get; set; }
        public Nullable<int> bAdvance { get; set; }
        public Nullable<int> iPay_Cd { get; set; }
        public Nullable<double> iAmount { get; set; }
        public int iFin_Cd { get; set; }
        public int iComp_Cd { get; set; }
        public int iBus_Cd { get; set; }
        public Nullable<int> iUser_Cd { get; set; }
        public Nullable<System.DateTime> dUpdate_Dt { get; set; }
        public Nullable<int> bActive { get; set; }
    }
}
