//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_BillMaster
    {
        public int BillMasterId { get; set; }
        public int iBill_No { get; set; }
        public Nullable<int> iComp_Cd { get; set; }
        public Nullable<int> iBus_Cd { get; set; }
    }
}
