//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing_Master_Vend
    {
        public int iBill_No { get; set; }
        public Nullable<System.DateTime> dBill_Dt { get; set; }
        public string sBillSRNo { get; set; }
        public Nullable<int> iVend_Cd { get; set; }
        public Nullable<double> TQty { get; set; }
        public Nullable<double> TAmt { get; set; }
        public Nullable<double> TGST { get; set; }
        public Nullable<double> TCESS { get; set; }
        public Nullable<double> TDiscount { get; set; }
        public Nullable<double> TDiscountValue { get; set; }
        public Nullable<double> TExtra { get; set; }
        public Nullable<double> TRoundOff { get; set; }
        public Nullable<double> iGrand_Amt { get; set; }
        public Nullable<byte> bDiscount { get; set; }
        public string sDis { get; set; }
        public int iFin_Cd { get; set; }
        public int iComp_Cd { get; set; }
        public int iBus_Cd { get; set; }
        public Nullable<int> iUser_Cd { get; set; }
        public Nullable<System.DateTime> dUpdate_Dt { get; set; }
        public string sType { get; set; }
    }
}
