//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing_Payment
    {
        public int iBill_No { get; set; }
        public double iPay_Amount { get; set; }
        public int iFin_Cd { get; set; }
        public int iComp_Cd { get; set; }
        public int iBus_Cd { get; set; }
        public int iUser_Cd { get; set; }
        public Nullable<System.DateTime> dUpdate_Dt { get; set; }
        public string sType { get; set; }
        public Nullable<int> iAcc_Cd { get; set; }
        public int iType { get; set; }
        public string sValue { get; set; }
        public string sCardValue { get; set; }
        public string sPaytmValue { get; set; }
    }
}
