//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing_Detail
    {
        public int AutoCode { get; set; }
        public int iBill_No { get; set; }
        public Nullable<int> iItem_Cd { get; set; }
        public string HSN { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> DisPer { get; set; }
        public Nullable<double> DisAmt { get; set; }
        public Nullable<double> ExtraAmt { get; set; }
        public Nullable<double> GSTPer { get; set; }
        public Nullable<double> GSTAmt { get; set; }
        public Nullable<double> CessPer { get; set; }
        public Nullable<double> CessAmt { get; set; }
        public Nullable<double> Total { get; set; }
        public string ItemDesc { get; set; }
        public int iFin_Cd { get; set; }
        public int iComp_Cd { get; set; }
        public int iBus_Cd { get; set; }
        public Nullable<int> bKOTPrint { get; set; }
        public Nullable<int> iSale_Cd { get; set; }
        public Nullable<int> iItemSr_No { get; set; }
        public Nullable<int> iKOT_No { get; set; }
        public Nullable<double> TaxAmt { get; set; }
        public Nullable<System.DateTime> dPunch_Time { get; set; }
        public Nullable<byte> bReady { get; set; }
    }
}
