//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_Master
    {
        public int iCat_Cd { get; set; }
        public string sCat_Nm { get; set; }
        public int iComp_Cd { get; set; }
        public int iBus_Cd { get; set; }
        public Nullable<int> iUser_Cd { get; set; }
        public Nullable<System.DateTime> dUpdate_Dt { get; set; }
    }
}
