//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Master
    {
        public int iComp_Cd { get; set; }
        public Nullable<int> ResturantID { get; set; }
        public string sComp_Nm { get; set; }
        public string Address { get; set; }
        public string TagLine { get; set; }
        public string GSTIN { get; set; }
        public string MobileNo { get; set; }
        public string ImgName { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public Nullable<int> iUser_Cd { get; set; }
        public Nullable<System.DateTime> dUpdate_Dt { get; set; }
        public string DBaseNm { get; set; }
        public string RefCode { get; set; }
    }
}
