//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configration_Master
    {
        public int iCodeNo { get; set; }
        public int iComp_Cd { get; set; }
        public int iBus_Cd { get; set; }
        public Nullable<byte> bCloud { get; set; }
        public Nullable<byte> bTab { get; set; }
        public Nullable<byte> bLocation { get; set; }
        public Nullable<byte> bMCode { get; set; }
        public Nullable<byte> BillSeries { get; set; }
        public Nullable<byte> bShowBillDate { get; set; }
        public Nullable<System.DateTime> OpDate { get; set; }
        public Nullable<byte> bKOTPrint { get; set; }
        public Nullable<byte> bBillPrint { get; set; }
        public Nullable<byte> iKOTNo { get; set; }
        public Nullable<byte> iBillNo { get; set; }
        public string sKOTLang { get; set; }
        public string sKOTType { get; set; }
        public string sBillPrinterType { get; set; }
        public string sBillTax { get; set; }
        public string sBillType { get; set; }
        public Nullable<byte> bKOTMsg { get; set; }
        public Nullable<byte> bBillMsg { get; set; }
        public Nullable<byte> iUser_Cd { get; set; }
        public Nullable<System.DateTime> dUpdate_Dt { get; set; }
        public Nullable<byte> bAddItem { get; set; }
        public Nullable<byte> bShowRemove { get; set; }
        public Nullable<byte> bLockRate { get; set; }
        public string SMSSenderID { get; set; }
        public string SMSKey { get; set; }
        public string SMSLang { get; set; }
        public string SMSNo { get; set; }
        public Nullable<byte> bDeleteSMS { get; set; }
        public Nullable<byte> bKOTPreview { get; set; }
        public Nullable<byte> bBillPreview { get; set; }
        public Nullable<byte> bQTPrint { get; set; }
        public string sQTPrinterType { get; set; }
        public Nullable<byte> bReverse { get; set; }
        public Nullable<byte> TTop { get; set; }
        public Nullable<byte> THigh { get; set; }
        public Nullable<byte> TWdth { get; set; }
        public Nullable<byte> bPax { get; set; }
        public Nullable<byte> bTabBillPrint { get; set; }
        public Nullable<byte> bItemFromCode { get; set; }
        public Nullable<byte> bLoyalty { get; set; }
        public Nullable<byte> bEBill { get; set; }
        public Nullable<byte> bBillSplit { get; set; }
        public Nullable<byte> bQRCode { get; set; }
        public Nullable<byte> bMobileNo { get; set; }
        public Nullable<byte> bGuestName { get; set; }
        public string sEBillType { get; set; }
        public Nullable<byte> bAttendent { get; set; }
        public Nullable<byte> bOnlineOrder { get; set; }
        public string TokenKey { get; set; }
        public Nullable<byte> iSMSType { get; set; }
        public Nullable<byte> bDeleteKOTPrint { get; set; }
    }
}
