//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustBillMaster
    {
        public System.Guid CustBillMasterID { get; set; }
        public string HotelName { get; set; }
        public string BillNumber { get; set; }
        public string TabelNumber { get; set; }
        public string BillDate { get; set; }
        public string SubTotal { get; set; }
        public string Discount { get; set; }
        public string TaxAmount { get; set; }
        public string Total { get; set; }
        public string RoundOff { get; set; }
        public string GrandTotal { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string TagLine { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string GST { get; set; }
        public string GuestName { get; set; }
        public Nullable<int> ResturantID { get; set; }
    }
}
