//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustBillItem
    {
        public int CustBillItemsId { get; set; }
        public System.Guid CustBillMasterID { get; set; }
        public string ItemName { get; set; }
        public string Rate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Amount { get; set; }
        public Nullable<int> ResturantID { get; set; }
    }
}
