//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Est_Billing
    {
        public int iBill_No { get; set; }
        public Nullable<System.DateTime> dDate { get; set; }
        public Nullable<System.DateTime> dPGDate { get; set; }
        public string sGuset { get; set; }
        public string sMobile { get; set; }
        public Nullable<int> iPax { get; set; }
        public Nullable<double> iRate { get; set; }
        public Nullable<double> iAmount { get; set; }
        public string Remark { get; set; }
        public Nullable<int> iItem_Cd { get; set; }
        public int iOrder { get; set; }
        public string sType { get; set; }
        public int iFin_Cd { get; set; }
        public int iComp_Cd { get; set; }
        public int iBus_Cd { get; set; }
        public Nullable<int> iUser_Cd { get; set; }
        public Nullable<System.DateTime> dUpdate_Dt { get; set; }
        public Nullable<double> iDis_Amt { get; set; }
        public Nullable<int> bDis { get; set; }
        public Nullable<double> iGrand_Amt { get; set; }
    }
}
