//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenses_Tran
    {
        public int iRec_Cd { get; set; }
        public Nullable<System.DateTime> dRec_Dt { get; set; }
        public Nullable<int> iPay_Cd { get; set; }
        public int iExp_Cd { get; set; }
        public Nullable<double> iAmount { get; set; }
        public string Remark { get; set; }
        public int iFin_Cd { get; set; }
        public int iComp_Cd { get; set; }
        public int iBus_Cd { get; set; }
        public Nullable<int> iUser_Cd { get; set; }
        public Nullable<System.DateTime> dUpdate_Dt { get; set; }
    }
}
