//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback_Tran
    {
        public int iFeedback_Trans_CD { get; set; }
        public int iFeed_Cd { get; set; }
        public Nullable<int> iAnswer { get; set; }
        public int iBill_No { get; set; }
        public int iComp_Cd { get; set; }
        public int iBus_Cd { get; set; }
        public Nullable<int> iUser_Cd { get; set; }
        public Nullable<System.DateTime> dUpdate_Dt { get; set; }
        public string sGuest_Name { get; set; }
        public string sMobile { get; set; }
        public Nullable<System.DateTime> dDOA { get; set; }
        public Nullable<System.DateTime> dDOB { get; set; }
        public string sEmail { get; set; }
        public string sCustomerReview { get; set; }
    }
}
