//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fin_Yr_Master
    {
        public int iFin_Yr_Cd { get; set; }
        public string sFin_Yr_Nm { get; set; }
        public Nullable<int> bDefault { get; set; }
    }
}
