//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodOrder_Item_Master
    {
        public decimal AutoCode { get; set; }
        public Nullable<decimal> Biz_Id { get; set; }
        public string Store_Id { get; set; }
        public Nullable<decimal> UPR_Order_Id { get; set; }
        public string Order_Id { get; set; }
        public string Item_Cd { get; set; }
        public string Item_Name { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> Item_Tax { get; set; }
        public Nullable<double> Item_Total { get; set; }
        public Nullable<double> Charges { get; set; }
        public Nullable<double> Discount { get; set; }
        public string Food_Type { get; set; }
        public string Options_To_Add_Title { get; set; }
        public string Options_To_Add_Rate { get; set; }
        public string Options_To_Remove { get; set; }
    }
}
