//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodOrder_Customer_Master
    {
        public decimal AutoCode { get; set; }
        public Nullable<decimal> Biz_Id { get; set; }
        public string Store_Id { get; set; }
        public Nullable<decimal> UPR_Order_Id { get; set; }
        public string Order_Id { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Address { get; set; }
        public string Customer_Phone { get; set; }
        public string Customer_Email { get; set; }
        public string Customer_Landmark { get; set; }
    }
}
