//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodOrder_Order_Status
    {
        public decimal AutoCode { get; set; }
        public string Store_Id { get; set; }
        public string Channel { get; set; }
        public Nullable<decimal> UPR_Order_Id { get; set; }
        public string Order_Id { get; set; }
        public string dUpdate_Dt { get; set; }
        public string Order_Status { get; set; }
        public string Order_Message { get; set; }
        public string Order_Status_Pre { get; set; }
    }
}
