//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodOrder_Rider_Status
    {
        public decimal AutoCode { get; set; }
        public string Store_Id { get; set; }
        public string Channel { get; set; }
        public Nullable<decimal> UPR_Order_Id { get; set; }
        public string Order_Id { get; set; }
        public string Current_State { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Alt_Phone { get; set; }
        public Nullable<decimal> User_Id { get; set; }
        public string Comments { get; set; }
        public string Created { get; set; }
        public string Status { get; set; }
    }
}
