//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodOrder_Order_Master
    {
        public decimal AutoCode { get; set; }
        public Nullable<decimal> Biz_Id { get; set; }
        public string Store_Id { get; set; }
        public string Channel { get; set; }
        public Nullable<decimal> UPR_Order_Id { get; set; }
        public string Order_Id { get; set; }
        public Nullable<double> Order_Subtotal { get; set; }
        public Nullable<double> Order_Tax { get; set; }
        public Nullable<double> Order_Total { get; set; }
        public string OrderTime { get; set; }
        public string DeliveryTime { get; set; }
        public Nullable<byte> OrderValue { get; set; }
        public Nullable<double> Order_Charges { get; set; }
        public string Order_Coupon { get; set; }
        public string Order_Instructions { get; set; }
        public string Charges_Title { get; set; }
        public Nullable<double> Charges_Value { get; set; }
        public Nullable<double> Order_Discount { get; set; }
        public Nullable<double> External_Discount { get; set; }
        public string Order_Type { get; set; }
        public string Delivery_Type { get; set; }
        public string Payment_Type { get; set; }
    }
}
