//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_Master
    {
        public int iCode { get; set; }
        public string sName { get; set; }
        public string sForm_Nm { get; set; }
        public Nullable<int> bActive { get; set; }
        public int iComp_Cd { get; set; }
        public int iBus_Cd { get; set; }
    }
}
