//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_Item_Master
    {
        public int AutoCode { get; set; }
        public int iCat_Cd { get; set; }
        public Nullable<int> iSale_Cd { get; set; }
        public int iItem_Cd { get; set; }
        public string sItem_Nm { get; set; }
        public Nullable<double> Rate { get; set; }
        public string HSN { get; set; }
        public Nullable<int> iUnit_Cd { get; set; }
        public Nullable<int> bActive { get; set; }
        public int iComp_Cd { get; set; }
        public int iBus_Cd { get; set; }
        public Nullable<int> iUser_Cd { get; set; }
        public Nullable<System.DateTime> dUpdate_Dt { get; set; }
        public Nullable<double> Waste { get; set; }
        public Nullable<byte> bGravy { get; set; }
    }
}
