//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Master
    {
        public int AutoCode { get; set; }
        public Nullable<int> iCat_Cd { get; set; }
        public Nullable<int> iSale_Cd { get; set; }
        public int iItem_Cd { get; set; }
        public string sItem_Nm { get; set; }
        public Nullable<double> Rate { get; set; }
        public string HSN { get; set; }
        public string MCode { get; set; }
        public Nullable<int> iMeal_Cd { get; set; }
        public string Hindi_Nm { get; set; }
        public Nullable<int> bVeg { get; set; }
        public Nullable<double> Rate1 { get; set; }
        public Nullable<double> Rate2 { get; set; }
        public Nullable<double> Rate3 { get; set; }
        public Nullable<double> Rate4 { get; set; }
        public Nullable<double> Rate5 { get; set; }
        public Nullable<int> bActive { get; set; }
        public string BarCode { get; set; }
        public int iComp_Cd { get; set; }
        public int iBus_Cd { get; set; }
        public Nullable<int> iUser_Cd { get; set; }
        public Nullable<System.DateTime> dUpdate_Dt { get; set; }
        public Nullable<int> bTop { get; set; }
        public Nullable<int> bDisApply { get; set; }
        public Nullable<byte> bQRCode { get; set; }
        public string sDesc { get; set; }
        public string sLabel_Nm { get; set; }
        public string sQR_Nm { get; set; }
        public Nullable<int> iItemOrder { get; set; }
        public Nullable<byte> bFoodOrder { get; set; }
        public Nullable<byte> bKDS { get; set; }
        public string sOnline_Nm { get; set; }
    }
}
