//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class KOT_Master
    {
        public int KotMasterId { get; set; }
        public int iUser_Cd { get; set; }
        public int iTab_Cd { get; set; }
        public int iItem_cd { get; set; }
        public double Qty { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Description { get; set; }
        public Nullable<int> iComp_Cd { get; set; }
        public Nullable<int> iBus_Cd { get; set; }
        public Nullable<int> iPax { get; set; }
        public Nullable<int> bProcess { get; set; }
        public string sGuestName { get; set; }
        public string sMobile { get; set; }
    }
}
