//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loyalty_Tran
    {
        public int AutoCode { get; set; }
        public Nullable<int> iTran_No { get; set; }
        public Nullable<System.DateTime> dDate { get; set; }
        public string sMobile { get; set; }
        public Nullable<double> iValue { get; set; }
        public Nullable<double> Point { get; set; }
        public string sType { get; set; }
        public int iComp_Cd { get; set; }
        public int iBus_Cd { get; set; }
        public Nullable<int> iUser_Cd { get; set; }
        public Nullable<System.DateTime> dUpdate_Dt { get; set; }
        public Nullable<byte> bActive { get; set; }
        public Nullable<byte> bAdd { get; set; }
        public string sRemark { get; set; }
        public Nullable<int> iLoyalty_Cd { get; set; }
    }
}
