//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loyalty_Master
    {
        public int AutoCode { get; set; }
        public int iCode { get; set; }
        public int iComp_Cd { get; set; }
        public int iBus_Cd { get; set; }
        public Nullable<double> MaxEarn { get; set; }
        public string PointSystem { get; set; }
        public Nullable<System.DateTime> dFromDt { get; set; }
        public Nullable<System.DateTime> dToDt { get; set; }
        public Nullable<byte> bMaxPer { get; set; }
        public Nullable<byte> bRedimBill { get; set; }
        public Nullable<double> MaxValue { get; set; }
        public Nullable<byte> bBirthdayPer { get; set; }
        public Nullable<byte> bBirthdayBill { get; set; }
        public Nullable<double> BirthdayValue { get; set; }
        public Nullable<byte> bAnniversaryPer { get; set; }
        public Nullable<byte> bAnniversaryBill { get; set; }
        public Nullable<double> AnniversaryValue { get; set; }
        public Nullable<byte> bActive { get; set; }
        public Nullable<int> iUser_Cd { get; set; }
        public Nullable<System.DateTime> dUpdate_Dt { get; set; }
        public Nullable<double> MinValue { get; set; }
        public Nullable<double> PerValue { get; set; }
        public Nullable<byte> bRoundOff { get; set; }
        public Nullable<double> FromAmt { get; set; }
        public Nullable<double> ToAmt { get; set; }
        public string Type { get; set; }
        public Nullable<double> Value { get; set; }
    }
}
