//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MasterEntities : DbContext
    {
        public MasterEntities()
            : base("name=MasterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Resturant> Resturants { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<CustBillItem> CustBillItems { get; set; }
        public virtual DbSet<CustBillMaster> CustBillMasters { get; set; }
    }
}
