//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Online_Item_Master
    {
        public string sRefId { get; set; }
        public int iItem_Cd { get; set; }
        public int iComp_Cd { get; set; }
        public int iBus_Cd { get; set; }
        public Nullable<byte> bOrder { get; set; }
        public Nullable<byte> bRecommd { get; set; }
        public Nullable<byte> bZomato { get; set; }
        public Nullable<byte> bSwiggy { get; set; }
        public Nullable<byte> bAmazon { get; set; }
        public string sTag_Nm { get; set; }
        public Nullable<byte> bCharge { get; set; }
    }
}
