//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Online_Master
    {
        public int iOnline_Cd { get; set; }
        public string sOnline_Nm { get; set; }
        public Nullable<double> Dis { get; set; }
        public Nullable<double> Comm { get; set; }
        public Nullable<double> GST { get; set; }
        public Nullable<double> PG { get; set; }
        public Nullable<int> iAcc_Cd { get; set; }
        public int iComp_Cd { get; set; }
        public int iBus_Cd { get; set; }
        public Nullable<int> iUser_Cd { get; set; }
        public Nullable<System.DateTime> dUpdate_Dt { get; set; }
    }
}
