//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outlet_Master
    {
        public int iCode { get; set; }
        public string sName { get; set; }
        public string sCity { get; set; }
        public string sAddress { get; set; }
        public string sRefId { get; set; }
        public Nullable<byte> bZomato { get; set; }
        public Nullable<byte> bSwiggy { get; set; }
        public Nullable<byte> bAmazon { get; set; }
        public Nullable<byte> bActive { get; set; }
        public Nullable<byte> bOrder { get; set; }
        public Nullable<System.DateTime> dUpdate_Dt { get; set; }
        public Nullable<int> iComp_Cd { get; set; }
        public Nullable<int> iBus_Cd { get; set; }
        public Nullable<byte> bZomato_Order { get; set; }
        public Nullable<byte> bSwiggy_Order { get; set; }
        public Nullable<byte> bAmazon_Order { get; set; }
    }
}
