//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe_Master
    {
        public string iMenu_Item_Cd { get; set; }
        public int iItem_Cd { get; set; }
        public int iCat_Cd { get; set; }
        public Nullable<double> Qty { get; set; }
        public int iComp_Cd { get; set; }
        public int iBus_Cd { get; set; }
        public Nullable<int> iUser_Cd { get; set; }
        public Nullable<System.DateTime> dUpdate_Dt { get; set; }
    }
}
