//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_Process
    {
        public Nullable<int> iTab_Cd { get; set; }
        public int iItem_Cd { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<byte> bProcess { get; set; }
    }
}
