//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Shift
    {
        public int AutoCode { get; set; }
        public int iBill_No { get; set; }
        public int iOld_Tab_Cd { get; set; }
        public int iNew_Tab_Cd { get; set; }
        public string sReason { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int iFin_Cd { get; set; }
        public int iComp_Cd { get; set; }
        public int iBus_Cd { get; set; }
    }
}
