//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Master
    {
        public int iUser_Cd { get; set; }
        public string sUser_Nm { get; set; }
        public string sFull_nm { get; set; }
        public Nullable<int> bAdmin { get; set; }
        public string sPIN { get; set; }
        public string sPassword { get; set; }
        public Nullable<byte> bAttd { get; set; }
        public Nullable<int> iAttd_Cd { get; set; }
        public Nullable<byte> bMultiCompany { get; set; }
    }
}
