//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor_Master
    {
        public Nullable<int> iGrp_Cd { get; set; }
        public int iVend_Cd { get; set; }
        public string sVend_Nm { get; set; }
        public string sAddress { get; set; }
        public string GSTNo { get; set; }
        public Nullable<int> iState_Cd { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string PANNo { get; set; }
        public string ConPerson { get; set; }
        public string CPerMob { get; set; }
        public int iComp_Cd { get; set; }
        public int iBus_Cd { get; set; }
        public Nullable<int> bActive { get; set; }
        public Nullable<int> sType { get; set; }
        public string sBank { get; set; }
        public string sBankAcc { get; set; }
        public string IFSC { get; set; }
    }
}
