//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Hour
    {
        public string Dt { get; set; }
        public Nullable<int> HR { get; set; }
        public Nullable<double> Amt { get; set; }
        public int iComp_Cd { get; set; }
        public int iBus_Cd { get; set; }
    }
}
