//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_RunningTable
    {
        public int iBill_No { get; set; }
        public Nullable<System.DateTime> dBill_Dt { get; set; }
        public Nullable<int> iTab_Cd { get; set; }
        public string sGuest_Nm { get; set; }
        public Nullable<byte> bPrint { get; set; }
        public Nullable<double> iGrand_Amt { get; set; }
        public Nullable<int> iPax { get; set; }
        public Nullable<System.DateTime> INTime { get; set; }
        public string sTab_Cat_Nm { get; set; }
        public int iTab_Cat_Cd { get; set; }
        public int iComp_Cd { get; set; }
        public int iBus_Cd { get; set; }
        public string sTab_Nm { get; set; }
        public Nullable<byte> bOpen { get; set; }
    }
}
