//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_BillPrint
    {
        public int iBill_No { get; set; }
        public Nullable<System.DateTime> dBill_Dt { get; set; }
        public Nullable<int> iTab_Cd { get; set; }
        public string sGuest_Nm { get; set; }
        public string sMobile { get; set; }
        public string sItem_Nm { get; set; }
        public Nullable<int> iItem_Cd { get; set; }
        public string HSN { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> TQty { get; set; }
        public Nullable<double> TAmount { get; set; }
        public int iCat_Cd { get; set; }
        public string sCat_Nm { get; set; }
        public int iComp_Cd { get; set; }
        public int iBus_Cd { get; set; }
        public int iFin_Cd { get; set; }
        public Nullable<double> TDis { get; set; }
        public Nullable<int> TTax { get; set; }
        public Nullable<int> iPax { get; set; }
        public string GSTIN { get; set; }
        public string sAttd_Nm { get; set; }
        public Nullable<byte> bDiscount { get; set; }
        public string sTab_Nm { get; set; }
        public Nullable<double> TRoundOff { get; set; }
        public Nullable<double> iGrand_Amt { get; set; }
        public Nullable<double> TExtra { get; set; }
        public Nullable<double> TTot { get; set; }
        public Nullable<double> TTExtra { get; set; }
        public Nullable<byte> bVoid { get; set; }
        public Nullable<byte> bOpen { get; set; }
        public Nullable<double> iWayOffAmt { get; set; }
        public string sTab_Cat_Nm { get; set; }
        public string sBillType { get; set; }
        public Nullable<int> iTab_Cat_Cd { get; set; }
        public Nullable<byte> bDepend { get; set; }
        public Nullable<byte> iDep_Cat_Cd { get; set; }
    }
}
