//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_TaxDetail
    {
        public int iSale_Cd { get; set; }
        public int iTax_Cd { get; set; }
        public int iComp_Cd { get; set; }
        public int iBus_Cd { get; set; }
        public Nullable<double> iPercentage { get; set; }
        public string sTax_Nm { get; set; }
        public string sSale_Nm { get; set; }
        public int iItem_Cd { get; set; }
        public string sItem_Nm { get; set; }
        public Nullable<int> bDepend { get; set; }
        public Nullable<int> iDepTax_Cd { get; set; }
    }
}
