//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhaoPiyoManagement_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Tran
    {
        public int iBill_No { get; set; }
        public Nullable<System.DateTime> dBill_Dt { get; set; }
        public Nullable<int> iTab_Cd { get; set; }
        public string sGuest_Nm { get; set; }
        public string sMobile { get; set; }
        public Nullable<int> iPax { get; set; }
        public string GSTIN { get; set; }
        public Nullable<int> iAttd_Cd { get; set; }
        public Nullable<double> TQty { get; set; }
        public Nullable<byte> bNC { get; set; }
        public string sNCReason { get; set; }
        public Nullable<double> TAmt { get; set; }
        public Nullable<double> TGST { get; set; }
        public Nullable<double> TCESS { get; set; }
        public Nullable<double> TDiscount { get; set; }
        public Nullable<double> TRoundOff { get; set; }
        public Nullable<double> iGrand_Amt { get; set; }
        public Nullable<byte> bDiscount { get; set; }
        public string sDis { get; set; }
        public Nullable<int> iDis_Cd { get; set; }
        public Nullable<byte> bPrint { get; set; }
        public Nullable<byte> bOpen { get; set; }
        public Nullable<byte> bLessStock { get; set; }
        public Nullable<System.DateTime> INTime { get; set; }
        public Nullable<byte> bVoid { get; set; }
        public int iFin_Cd { get; set; }
        public int iComp_Cd { get; set; }
        public int iBus_Cd { get; set; }
        public Nullable<int> iUser_Cd { get; set; }
        public Nullable<System.DateTime> dUpdate_Dt { get; set; }
        public string sAttd_Nm { get; set; }
        public string sDis_Nm { get; set; }
        public string sItem_Nm { get; set; }
        public Nullable<int> iItem_Cd { get; set; }
        public string HSN { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> DisPer { get; set; }
        public Nullable<double> DisAmt { get; set; }
        public Nullable<double> GSTPer { get; set; }
        public Nullable<double> GSTAmt { get; set; }
        public Nullable<double> CessPer { get; set; }
        public Nullable<double> CessAmt { get; set; }
        public Nullable<double> Total { get; set; }
        public string ItemDesc { get; set; }
        public Nullable<int> bKOTPrint { get; set; }
        public Nullable<int> iItemSr_No { get; set; }
        public Nullable<int> iSale_Cd { get; set; }
        public Nullable<int> iKOT_No { get; set; }
        public Nullable<double> TaxAmt { get; set; }
        public string sType { get; set; }
        public Nullable<int> iAcc_Cd { get; set; }
        public string sDis_Type { get; set; }
        public int iCat_Cd { get; set; }
        public string sCat_Nm { get; set; }
        public int iMeal_Cd { get; set; }
        public string sMeal_Nm { get; set; }
        public Nullable<double> TDiscountValue { get; set; }
        public string sTab_Nm { get; set; }
        public Nullable<double> ExtraAmt { get; set; }
        public Nullable<double> TExtra { get; set; }
        public Nullable<double> NCAmt { get; set; }
        public Nullable<int> iRef_Cd { get; set; }
        public Nullable<double> iWayOffAmt { get; set; }
        public string iWayOffRemark { get; set; }
        public Nullable<double> iTipAmt { get; set; }
        public Nullable<double> iDonationAmt { get; set; }
        public string iTipRemark { get; set; }
        public string iDonationRemark { get; set; }
        public string MCode { get; set; }
        public string sTab_Cat_Nm { get; set; }
        public string sVoidReason { get; set; }
        public string sBillType { get; set; }
        public string sRef_Nm { get; set; }
        public Nullable<System.DateTime> dPunch_Time { get; set; }
        public Nullable<byte> bReady { get; set; }
        public Nullable<int> iTab_Cat_Cd { get; set; }
        public int AutoCode { get; set; }
        public Nullable<byte> bDepend { get; set; }
        public Nullable<byte> iDep_Cat_Cd { get; set; }
        public Nullable<byte> bKDS { get; set; }
    }
}
